export const postsData = [
    {
        title: "next Js Image",
        image: "post1.png",
        slug: "some thing",
        excerpt: "hello there this is my first post in next js test, hello there this is my first post in next js test, hello there this is my first post in next js test",
        date: "2021-4-2",
    },
    {
        title: "next Js Image",
        image: "post2.jpeg",
        slug: "some thing",
        excerpt: "hello there this is my first post in next js test, hello there this is my first post in next js test, hello there this is my first post in next js test",
        date: "2021-4-2",
    },
    {
        title: "next Js Image",
        image: "post3.jfif",
        slug: "some thing",
        excerpt: "hello there this is my first post in next js test, hello there this is my first post in next js test, hello there this is my first post in next js test",
        date: "2021-4-2",
    },
    {
        title: "next Js Image",
        image: "post4.jfif",
        slug: "some thing",
        excerpt: "hello there this is my first post in next js test, hello there this is my first post in next js test, hello there this is my first post in next js test",
        date: "2021-4-2",
    },
    {
        title: "next Js Image",
        image: "post5.jpg",
        slug: "some thing",
        excerpt: "hello there this is my first post in next js test, hello there this is my first post in next js test, hello there this is my first post in next js test",
        date: "2021-4-2",
    },
    {
        title: "next Js Image",
        image: "post3.jfif",
        slug: "some thing",
        excerpt: "hello there this is my first post in next js test, hello there this is my first post in next js test, hello there this is my first post in next js test",
        date: "2021-4-2",
    },
    {
        title: "next Js Image",
        image: "post4.jfif",
        slug: "some thing",
        excerpt: "hello there this is my first post in next js test, hello there this is my first post in next js test, hello there this is my first post in next js test",
        date: "2021-4-2",
    },
    {
        title: "next Js Image",
        image: "post5.jpg",
        slug: "some thing",
        excerpt: "hello there this is my first post in next js test, hello there this is my first post in next js test, hello there this is my first post in next js test",
        date: "2021-4-2",
    },
    {
        title: "next Js Image",
        image: "post3.jfif",
        slug: "some thing",
        excerpt: "hello there this is my first post in next js test, hello there this is my first post in next js test, hello there this is my first post in next js test",
        date: "2021-4-2",
    },
    {
        title: "next Js Image",
        image: "post4.jfif",
        slug: "some thing",
        excerpt: "hello there this is my first post in next js test, hello there this is my first post in next js test, hello there this is my first post in next js test",
        date: "2021-4-2",
    },
    {
        title: "next Js Image",
        image: "post5.jpg",
        slug: "some thing",
        excerpt: "hello there this is my first post in next js test, hello there this is my first post in next js test, hello there this is my first post in next js test",
        date: "2021-4-2",
    },
];
